
language: r
sudo: false
cache: packages

r:
 - oldrel
 - release
 - devel

r_packages:
  - covr

warnings_are_errors: true

r_check_args: --as-cran

r_build_args: --resave-data

after_success:
  - Rscript -e 'library(covr); codecov()'
  - bash <(curl -s https://codecov.io/bash)
